production:
  S3KEY: AKIAJ3QKPTPMBQD6ALUQ
  S3SEC: koyEYnSU/siQ3ziScnMnlk0wR8KbkDgVyfHeIzL9
  bucket: nwv.fb.contest.pro
 
development:
  S3KEY: AKIAJ3QKPTPMBQD6ALUQ
  S3SEC: koyEYnSU/siQ3ziScnMnlk0wR8KbkDgVyfHeIzL9
  bucket: nwv.fb.contest.dev
 
test:
  S3KEY: AKIAJ3QKPTPMBQD6ALUQ
  S3SEC: koyEYnSU/siQ3ziScnMnlk0wR8KbkDgVyfHeIzL9
  bucket: nwv.fb.contest.dev