production:
  S3KEY: AKIAJ3QKPTPMBQD6ALUQ
  S3SEC: koyEY
  bucket: nwv.fb.contest.pro
 
development:
  S3KEY: AKIAJ3QKPTPMBQD6ALUQ
  S3SEC: koyEY
  bucket: nwv.fb.contest.dev
 
test:
  S3KEY: AKIAJ3QKPTPMBQD6ALUQ
  S3SEC: koyEY
  bucket: nwv.fb.contest.dev